services:
  postgres:
    image: postgres
    container_name: postgres_prisma
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sirefo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
